import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Title } from '../components/Title/Title';
import { Cards } from '../components/Cards/Cards';
import styles from '../styles/Home.module.css';
import data from '../data/profil.json';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kevin LE FRANC</title>
        <meta name="description" content="Portfolio generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title />
        <div className="mt-6">
          <h2 className="text-center mt-4 mb-4 text-4xl">My professionnal projects</h2>
          <ul className="grid grid-cols-3 gap-4 justify-items-center mt-4">
            {
              data.experiences.map((experience: any) => {
                return <Cards key={experience.id} {...experience} />;
              })
            }
          </ul>
        </div>
      </main>
    </div>
  );
};

export default Home;
